{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docmost.secretName" . }}
  labels:
    {{- include "docmost.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.secrets.appSecret | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  REDIS_URL: {{ include "docmost.redisUrl" . | quote }}
  {{- if eq .Values.config.storage.driver "s3" }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.aws.secretAccessKey | quote }}
  {{- end }}
  MAIL_DRIVER: {{ .Values.secrets.mail.driver | quote }}
  SMTP_HOST: {{ .Values.secrets.mail.smtp.host | quote }}
  SMTP_PORT: {{ .Values.secrets.mail.smtp.port | quote }}
  SMTP_USERNAME: {{ .Values.secrets.mail.smtp.username | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.mail.smtp.password | quote }}
  SMTP_SECURE: {{ .Values.secrets.mail.smtp.secure | quote }}
  MAIL_FROM_ADDRESS: {{ .Values.secrets.mail.fromAddress | quote }}
{{- end }}
