{{- if .Values.docmost.storage.local.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "docmost.fullname" . }}-storage
  labels:
    {{- include "docmost.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.docmost.storage.local.persistence.size }}
  {{- if .Values.docmost.storage.local.persistence.storageClass }}
  storageClassName: {{ .Values.docmost.storage.local.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
