apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docmost.fullname" . }}
type: Opaque
stringData:
  appSecret: {{ required "docmost.appSecret is required" .Values.docmost.appSecret | quote }}
  smtpHost: {{ default "" .Values.docmost.smtp.host | quote }}
  smtpPort: {{ default 465 .Values.docmost.smtp.port | toString | quote }}
  smtpUser: {{ default "" .Values.docmost.smtp.user | quote }}
  smtpPass: {{ default "" .Values.docmost.smtp.pass | quote }}
  smtpSecure: {{ ternary "true" "false" (default true .Values.docmost.smtp.secure) | quote }}
  smtpFrom: {{ default "" .Values.docmost.smtp.from | quote }}
