apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docmost.fullname" . }}
data:
  appSecret: {{ .Values.docmost.appSecret | b64enc | quote }}
  smtpHost: {{ .Values.docmost.smtp.host | b64enc | quote }}
  smtpPort: {{ .Values.docmost.smtp.port | b64enc | quote }}
  smtpUser: {{ .Values.docmost.smtp.user | b64enc | quote }}
  smtpPass: {{ .Values.docmost.smtp.pass | b64enc | quote }}
  smtpSecure: {{ .Values.docmost.smtp.secure | b64enc | quote }}
  smtpFrom: {{ .Values.docmost.smtp.from | b64enc | quote }}
type: Opaque

